### ISSUE TITLE
Paleodatabase search error 403 "forbidden"

### ISSUE THREAD

**Issue by jmich2912** [paleobiodb/PBDB_changelog#64]
When trying to look at collections of genera, I receive a 403 error with "forbidden" displayed underneath. I have no idea what the issue is, and I haven't had this happen to me before. I love looking at the various collections in the database, so any assistance would be greatly appreciated.

**Comment by pnovack-gottshall** [comment]
This should be fixed now. The 403 error happens from time to time when there's a server processing error. These usually resolve themselves within a few minutes to an hour (rarely overnight). The server now seems to be working correctly, so I'm closing the issue

**Comment by Prowlbeast** [comment]
Hi, I had this happen to me continuously tonight as well. I use PBDB daily and this is a big roadblock for me :( "403 Forbidden
nginx" for hours!

Prowl

**Comment by pnovack-gottshall** [comment]
The 403 Forbidden error tends to occur if you manually go to a PBDB page (e.g., https://paleobiodb.org/classic/basicTaxonInfo?taxon_no=txn:210725) instead of using the GUI. I recall they disabled the ability to manually view pages to cut down on the dramatic increase in AI bots using the API that way (which overloads the server so no one can use the site).

You can usually avoid it by using the GUI to navigate pages. If you have a valid reason to manually visit sites, back channel me (pnovack-gottshall at ben dot edu) and I can show you a hack that usually works.

**Comment by mmcclenn** [comment]
I had to add checkTaxonInfo and basicTaxonInfo to the list of pages that will get a 403 unless there is a referer page, because we got hit by a scraper bot that was bringing the server to its knees. Can you tell me exactly what you are doing that gets the 403 error? I will see if I can find a solution that blocks the bot without blocking you.

**Comment by Prowlbeast** [comment]
hi. I didnt do anything crazy, I just typed in a taxon using the search bar. as a sidenote, im experiencing even more strange symptoms now. 

I now cant even access anything other than the maijn page. I can open the main page but trying to open a taxon leads to disconnection? is there maintenance atm?

<img width="1105" height="513" alt="Image" src="https://github.com/user-attachments/assets/68d96abc-3b32-458e-9e73-b7aab49a4e09" />

**Comment by mmcclenn** [comment]
The problems you had connecting to the site were transient. It crashed around 9:20 pm, and it took me a while to get it back up. Thank you for pointing out the 403 problem, with the main search box, however. I have now fixed that, and made some other improvements to the search function as well.

**Comment by Prowlbeast** [comment]
Hi,

Glad to hear it! I am however still getting 403 errors. If it is permission dependent and permanently blocking me, is there a way to email somebody to unblock my IP? I saw in another bug report that there was an email one could contact about issues with permission?

**Comment by Prowlbeast** [comment]
I dont think its a problem that is your fault at all, I use PBDB a lot so I may just be being detected as a bot!
<img width="1669" height="1021" alt="Image" src="https://github.com/user-attachments/assets/22170a9f-0605-4df2-8a4a-cfb37a37ea11" />

**Comment by mmcclenn** [comment]
I am the person who is responsible for unblocking, and if you tell me your IP address I can easily check if you are being blocked. However, I think the problem is more likely that you need to do a full reload of the PaleoBioDB home page (command-shift-R in most browsers) in order to stop getting the 403 errors. A full reload will cause your browser to reload all of the Javascript files associated with the home page so that it will get my code update.

**Comment by Prowlbeast** [comment]
Hi,

It works! I am able to access PBDB today! :D

Thank You All!

**Comment by mmcclenn** [comment]
Great! I am glad to hear that.
