### ISSUE TITLE
Metadata license information incorrect

### ISSUE THREAD

**Issue by bethany-j-allen** [paleobiodb/PBDB_changelog#68]
I've just noticed that the metadata header on data downloads states that PBDB data is under a CC-BY license.

<img width="556" alt="Image" src="https://github.com/user-attachments/assets/986688f5-93b7-4534-86a8-4cdbc8ae9966" />

The committee shifted this position in the recent past and agreed to put the data under a CC0 license, as stated in the website FAQs.

<img width="809" alt="Image" src="https://github.com/user-attachments/assets/fa73e79a-9a9d-471e-baac-b674c12214b7" />

It would be ideal to update the metadata header to align with this change.

**Comment by cambro** [comment]
Thank you for bringing this to our attention! Not sure how we missed that, but we will be sure to fix it soon.

**Comment by mmcclenn** [comment]
This is now fixed. The API responses all say CC0, and give the appropriate URL for the license terms.

**Comment by cambro** [comment]
@mmcclenn this issue is still present on many PBDB assets, including classic. will submit bug there.
